spring.datasource.url=jdbc:postgresql://localhost:5432/saga
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=saga
spring.datasource.password=secret
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect