apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress
  template:
    metadata:
      labels:
        app: ingress
    spec:
      containers:
        - name: ingress
          image: "{{ .Values.ingress.image }}:{{ .Values.ingress.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_URL
              value: "http://ingress:9000"   # adjust port if needed
            - name: NODE_URL
              value: "http://ingress:8080"      # or your service name
            - name: NODE_PORT
              value: "8080"