apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node
          image: "{{ .Values.node.image }}:{{ .Values.node.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: REGISTRY_URL
              value: "http://ingress:8080"   # adjust port if needed
            - name: NODE_URL
              value: "http://node:8080"      # or your service name
            - name: NODE_PORT
              value: "8080"